- name: Config elk VM with Docker
  hosts: elk
  become: true
  tasks:
    - name: docker.io
      apt:
        force_apt_get: yes      
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present
    
    - name: Install Python Docker module
      pip:
        name: docker
        state: present
   
    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: sebp/elk:761
        state: started
        published_ports: 80:80
        ports:
         - 5601:5601
         - 9200:9200
         - 5044:5044

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes

    - ansible.posix.sysctl:
      	name: vm.max_map_count
        value: 262144
